name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install sitemap generator
        run: npm install -g sitemap-generator-cli

      - name: Determine site URL
        id: siteurl
        run: |
          if [ -f CNAME ]; then
            domain=$(cat CNAME | tr -d '[:space:]')
            echo "url=https://$domain" >> $GITHUB_OUTPUT
          else
            echo "CNAME file not found. Skipping sitemap generation."
            echo "skip=true" >> $GITHUB_OUTPUT

      - name: Generate sitemap
        if: steps.siteurl.outputs.skip != 'true'
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 1
        run: |
          sitemap-generator ${{ steps.siteurl.outputs.url }} --strip-querystring -d ./sitemap-tmp --verbose
          if [ -f ./sitemap-tmp/sitemap.xml ]; then
            mv ./sitemap-tmp/sitemap.xml ./sitemap.xml
          else
            echo "sitemap.xml not found. Skipping commit."
            exit 0
          fi

      - name: Commit and push sitemap
        if: steps.siteurl.outputs.skip != 'true' && (steps.generate-sitemap.outputs.skipped != 'true')
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes to commit"
          git push
